 INSERT INTO BALLOTS 
 (ID,ACTIVE, CREATED_AT, UPDATED_AT, VALUE, QUANTITY) 
 VALUES 
 (RANDOM_UUID(), 1, CURRENT_DATE(), CURRENT_DATE(), 100, 5),
 (RANDOM_UUID(), 1, CURRENT_DATE(), CURRENT_DATE(), 50, 5),
 (RANDOM_UUID(), 1, CURRENT_DATE(), CURRENT_DATE(), 20, 5),
 (RANDOM_UUID(), 1, CURRENT_DATE(), CURRENT_DATE(), 10, 5),
 (RANDOM_UUID(), 1, CURRENT_DATE(), CURRENT_DATE(), 5, 5)
 ; 